<?php

namespace App\Http\Controllers;

use App\Models\LocalDataMedian;
use App\Models\PgDataMedian;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class PgDataMedianSyncController extends Controller
{
    public function sync(Request $request)
    {
        $scopeParam = $request->query('scope', $request->input('scope', null));
        $scope = $scopeParam !== null ? trim((string) $scopeParam) : '';
        $offset = max(0, (int) $request->query('offset', $request->input('offset', 0)));
        $limit = (int) $request->query('limit', $request->input('limit', 300));
        $month = $request->query('month', $request->input('month'));
        $medianGroup = $request->query('median_group', $request->input('median_group'));
        $dryRun = filter_var(
            $request->query('dry_run', $request->input('dry_run', false)),
            FILTER_VALIDATE_BOOLEAN
        );

        if ($limit < 50) {
            $limit = 50;
        }
        if ($limit > 2000) {
            $limit = 2000;
        }

        $allScopes = ['ward', 'region', 'region_total', 'project', 'street'];
        $isFull = ($scope === '' || strtolower($scope) === 'all' || strtolower($scope) === 'full');
        if (!$isFull && !in_array($scope, $allScopes, true)) {
            return response()->json([
                'ok' => false,
                'error' => "Unsupported scope '{$scope}'. Supported: ward, region, region_total, project, street or empty(for full)",
            ], 422);
        }

        $this->ensurePgMedianTable();

        $scopesToRun = $isFull ? $allScopes : [$scope];
        $processedTotal = 0;
        $upsertedTotal = 0;
        $batchesTotal = 0;
        $perScope = [];

        foreach ($scopesToRun as $currentScope) {
            $currentOffset = $offset;
            $scopeProcessed = 0;
            $scopeUpserted = 0;
            $scopeBatches = 0;

            while (true) {
                $localRows = $this->loadLocalRows($currentScope, $currentOffset, $limit, $month, $medianGroup);
                if (empty($localRows)) {
                    break;
                }

                $rowCount = count($localRows);
                $scopeProcessed += $rowCount;
                $scopeUpserted += $rowCount;
                $scopeBatches++;

                if (!$dryRun) {
                    PgDataMedian::query()->upsert(
                        $localRows,
                        ['scope', 'new_region_id', 'new_ward_id', 'street_id', 'project_id', 'type', 'median_group', 'month'],
                        ['category', 'avg_price_m2', 'median_price_m2', 'min_price_m2', 'max_price_m2', 'total_rows', 'trimmed_rows', 'converted_at']
                    );
                }

                $currentOffset += $limit;
            }

            $perScope[$currentScope] = [
                'processed_rows' => $scopeProcessed,
                'upserted_rows' => $scopeUpserted,
                'batches' => $scopeBatches,
            ];
            $processedTotal += $scopeProcessed;
            $upsertedTotal += $scopeUpserted;
            $batchesTotal += $scopeBatches;
        }

        return response()->json([
            'ok' => true,
            'scope' => $isFull ? 'full' : $scope,
            'scopes' => $scopesToRun,
            'offset' => $offset,
            'limit' => $limit,
            'processed_rows' => $processedTotal,
            'upserted_rows' => $upsertedTotal,
            'batches' => $batchesTotal,
            'per_scope' => $perScope,
            'done' => true,
            'dry_run' => $dryRun,
        ]);
    }

    private function ensurePgMedianTable(): void
    {
        DB::connection('pgsql')->statement("
            CREATE TABLE IF NOT EXISTS data_median (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                scope VARCHAR(16) NOT NULL,
                new_region_id INTEGER NULL,
                new_ward_id INTEGER NULL,
                street_id INTEGER NULL,
                project_id INTEGER NULL,
                type VARCHAR(16) NULL,
                category INTEGER NULL,
                median_group SMALLINT NULL,
                month VARCHAR(7) NULL,
                avg_price_m2 NUMERIC(20,2) NULL,
                median_price_m2 NUMERIC(20,2) NULL,
                min_price_m2 NUMERIC(20,2) NULL,
                max_price_m2 NUMERIC(20,2) NULL,
                total_rows INTEGER NULL,
                trimmed_rows INTEGER NULL,
                converted_at TIMESTAMP NULL
            )
        ");

        DB::connection('pgsql')->statement("
            CREATE UNIQUE INDEX IF NOT EXISTS uq_scope_key
            ON data_median (scope, new_region_id, new_ward_id, street_id, project_id, type, median_group, month)
        ");
        DB::connection('pgsql')->statement("
            CREATE INDEX IF NOT EXISTS idx_scope_region
            ON data_median (scope, new_region_id)
        ");
        DB::connection('pgsql')->statement("
            CREATE INDEX IF NOT EXISTS idx_scope_ward
            ON data_median (scope, new_ward_id)
        ");
        DB::connection('pgsql')->statement("
            CREATE INDEX IF NOT EXISTS idx_scope_project
            ON data_median (scope, project_id)
        ");
        DB::connection('pgsql')->statement("
            CREATE INDEX IF NOT EXISTS idx_scope_street
            ON data_median (scope, street_id)
        ");
        DB::connection('pgsql')->statement("
            CREATE INDEX IF NOT EXISTS idx_month
            ON data_median (month)
        ");
    }

    private function loadLocalRows(string $scope, int $offset, int $limit, $month, $medianGroup): array
    {
        $q = LocalDataMedian::query()->where('scope', $scope);

        if (!empty($month)) {
            $q->where('month', (string) $month);
        }
        if ($medianGroup !== null && $medianGroup !== '') {
            $q->where('median_group', (int) $medianGroup);
        }

        return $q->orderBy('id')
            ->offset($offset)
            ->limit($limit)
            ->get()
            ->map(static function ($r) {
            return [
                'scope' => $r->scope,
                'new_region_id' => $r->new_region_id !== null ? (int) $r->new_region_id : null,
                'new_ward_id' => $r->new_ward_id !== null ? (int) $r->new_ward_id : null,
                'street_id' => $r->street_id !== null ? (int) $r->street_id : null,
                'project_id' => $r->project_id !== null ? (int) $r->project_id : null,
                'type' => $r->type,
                'category' => $r->category !== null ? (int) $r->category : null,
                'median_group' => $r->median_group !== null ? (int) $r->median_group : null,
                'month' => (string) $r->month,
                'avg_price_m2' => $r->avg_price_m2,
                'median_price_m2' => $r->median_price_m2,
                'min_price_m2' => $r->min_price_m2,
                'max_price_m2' => $r->max_price_m2,
                'total_rows' => $r->total_rows !== null ? (int) $r->total_rows : null,
                'trimmed_rows' => $r->trimmed_rows !== null ? (int) $r->trimmed_rows : null,
                'converted_at' => $r->converted_at ?? now(),
            ];
        })->all();
    }
}
