#!/usr/bin/env python3
import argparse
import csv
import os
import subprocess
import tempfile
from pathlib import Path

import pymysql
from pymysql.cursors import SSDictCursor

MYSQL_CONFIG = {
    'host': os.getenv('MYSQL_HOST', '127.0.0.1'),
    'port': int(os.getenv('MYSQL_PORT', '3306')),
    'user': os.getenv('MYSQL_USER', 'root'),
    'password': os.getenv('MYSQL_PASSWORD', ''),
    'database': os.getenv('MYSQL_DATABASE', 'craw_db'),
    'charset': 'utf8mb4',
    'cursorclass': SSDictCursor,
}

PG_CONFIG = {
    'host': os.getenv('PG_HOST', '118.69.81.54'),
    'port': os.getenv('PG_PORT', '35432'),
    'user': os.getenv('PG_USERNAME', 'reportuser'),
    'password': os.getenv('PG_PASSWORD', 'klcjalksjc1n1c1k1cckn1n'),
    'database': os.getenv('PG_DATABASE', 'report'),
    'schema': os.getenv('PG_SCHEMA', 'public'),
}

COLUMNS = [
    'period_type', 'period_value', 'scope',
    'province_id', 'ward_id', 'street_id', 'median_group',
    'raw_rows', 'trimmed_rows',
    'median_price_m2', 'stddev_price_m2', 'cv', 'vitality_score',
    'liquidity_level', 'median_source', 'computed_at',
]

CREATE_SQL = """
CREATE TABLE IF NOT EXISTS {schema}.thanhkhoan_index (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    period_type VARCHAR(10) NOT NULL,
    period_value VARCHAR(10) NOT NULL,
    scope VARCHAR(16) NOT NULL,
    province_id INTEGER NULL,
    ward_id INTEGER NULL,
    street_id INTEGER NULL,
    median_group SMALLINT NOT NULL,
    raw_rows INTEGER NOT NULL,
    trimmed_rows INTEGER NOT NULL,
    median_price_m2 NUMERIC(20,2) NULL,
    stddev_price_m2 NUMERIC(20,2) NULL,
    cv NUMERIC(20,6) NULL,
    vitality_score NUMERIC(20,6) NULL,
    liquidity_level VARCHAR(32) NULL,
    median_source VARCHAR(16) NOT NULL DEFAULT 'python',
    computed_at TIMESTAMP NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_thanhkhoan_index
ON {schema}.thanhkhoan_index (period_type, period_value, scope, province_id, ward_id, street_id, median_group);
CREATE INDEX IF NOT EXISTS idx_tk_period ON {schema}.thanhkhoan_index (period_type, period_value);
CREATE INDEX IF NOT EXISTS idx_tk_scope ON {schema}.thanhkhoan_index (scope, province_id, ward_id, street_id);
CREATE INDEX IF NOT EXISTS idx_tk_group ON {schema}.thanhkhoan_index (median_group);
"""


def mysql_conn():
    return pymysql.connect(**MYSQL_CONFIG)


def export_csv(csv_path: Path) -> int:
    sql = """
    SELECT period_type, period_value, scope,
           province_id, ward_id, street_id, median_group,
           raw_rows, trimmed_rows,
           median_price_m2, stddev_price_m2, cv, vitality_score,
           liquidity_level, median_source, computed_at
    FROM thanhkhoan_index
    ORDER BY id
    """
    total = 0
    conn = mysql_conn()
    try:
        with conn.cursor() as cur, csv_path.open('w', newline='', encoding='utf-8') as f:
            writer = csv.writer(f)
            cur.execute(sql)
            for row in cur:
                writer.writerow(['\\N' if row[col] is None else row[col] for col in COLUMNS])
                total += 1
    finally:
        conn.close()
    return total


def run_psql(sql: str):
    env = os.environ.copy()
    env['PGPASSWORD'] = PG_CONFIG['password']
    cmd = [
        'psql',
        '-h', PG_CONFIG['host'],
        '-p', str(PG_CONFIG['port']),
        '-U', PG_CONFIG['user'],
        '-d', PG_CONFIG['database'],
        '-v', 'ON_ERROR_STOP=1',
        '-c', sql,
    ]
    subprocess.run(cmd, check=True, env=env)


def run_psql_file(sql_path: Path):
    env = os.environ.copy()
    env['PGPASSWORD'] = PG_CONFIG['password']
    cmd = [
        'psql',
        '-h', PG_CONFIG['host'],
        '-p', str(PG_CONFIG['port']),
        '-U', PG_CONFIG['user'],
        '-d', PG_CONFIG['database'],
        '-v', 'ON_ERROR_STOP=1',
        '-f', str(sql_path),
    ]
    subprocess.run(cmd, check=True, env=env)


def main():
    ap = argparse.ArgumentParser(description='Sync thanhkhoan_index MySQL -> PostgreSQL')
    ap.add_argument('--truncate', action='store_true', help='Truncate PG table before load')
    ap.add_argument('--keep-csv', action='store_true', help='Keep exported CSV file')
    args = ap.parse_args()

    schema = PG_CONFIG['schema']
    run_psql(CREATE_SQL.format(schema=schema))
    if args.truncate:
        run_psql(f'TRUNCATE TABLE {schema}.thanhkhoan_index')

    tmp_dir = Path(tempfile.mkdtemp(prefix='thanhkhoan_pg_'))
    csv_path = tmp_dir / 'thanhkhoan_index.csv'
    sql_path = tmp_dir / 'load_thanhkhoan_index.sql'

    total = export_csv(csv_path)
    print(f'exported_rows={total}')

    copy_cols = ', '.join(COLUMNS)
    sql_path.write_text(f"""
BEGIN;
CREATE TEMP TABLE tmp_thanhkhoan_index AS
SELECT {copy_cols}
FROM {schema}.thanhkhoan_index
WHERE 1=0;
ALTER TABLE tmp_thanhkhoan_index DROP COLUMN IF EXISTS id;
\\copy tmp_thanhkhoan_index ({copy_cols}) FROM '{csv_path}' WITH (FORMAT csv, NULL '\\N');
INSERT INTO {schema}.thanhkhoan_index ({copy_cols})
SELECT {copy_cols}
FROM tmp_thanhkhoan_index
ON CONFLICT (period_type, period_value, scope, province_id, ward_id, street_id, median_group)
DO UPDATE SET
    raw_rows = EXCLUDED.raw_rows,
    trimmed_rows = EXCLUDED.trimmed_rows,
    median_price_m2 = EXCLUDED.median_price_m2,
    stddev_price_m2 = EXCLUDED.stddev_price_m2,
    cv = EXCLUDED.cv,
    vitality_score = EXCLUDED.vitality_score,
    liquidity_level = EXCLUDED.liquidity_level,
    median_source = EXCLUDED.median_source,
    computed_at = EXCLUDED.computed_at;
COMMIT;
""".strip() + "\n", encoding='utf-8')

    run_psql_file(sql_path)
    run_psql(f"SELECT COUNT(*) AS total_rows FROM {schema}.thanhkhoan_index")

    if not args.keep_csv:
        try:
            csv_path.unlink(missing_ok=True)
            sql_path.unlink(missing_ok=True)
            tmp_dir.rmdir()
        except Exception:
            pass


if __name__ == '__main__':
    main()
